package vn.struts.entity;
// Generated Apr 21, 2019 11:34:21 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "fishshop")
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4606015734324842838L;
	private Integer id;
	private Catalog catalog;
	private String name;
	private long price;
	private String content;
	private String image;
	private Date created;
	private int view;
	private Set<Order> orders = new HashSet<Order>(0);

	public Product() {
	}

	public Product(Catalog catalog, String name, long price, String content, String image, int view) {
		this.catalog = catalog;
		this.name = name;
		this.price = price;
		this.content = content;
		this.image = image;
		this.view = view;
	}

	public Product(Catalog catalog, String name, long price, String content, String image, Date created, int view,
			Set<Order> orders) {
		this.catalog = catalog;
		this.name = name;
		this.price = price;
		this.content = content;
		this.image = image;
		this.created = created;
		this.view = view;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "catalog_id", nullable = false)
	public Catalog getCatalog() {
		return this.catalog;
	}

	public void setCatalog(Catalog catalog) {
		this.catalog = catalog;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false)
	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "image", nullable = false, length = 50)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "view", nullable = false)
	public int getView() {
		return this.view;
	}

	public void setView(int view) {
		this.view = view;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "product")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
